### ISSUE TITLE
Mkae sure that address element has a new field called `Date Moved`

### ISSUE THREAD

**Issue by prateekjadhwani** [DamandeepS/Mobility#24]
Add a new field in `<address-element>` from the `feature-address-element` branch called `date moved`. It should accept a date and then store it locally.

**Comment by chandrag001** [comment]
Added  a new field date moved and stored locally

**Comment by chandrag001** [comment]
https://github.com/DamandeepS/Mobility/pull/27

link to the pull request issue#24
